### ISSUE TITLE
Better integration with WikiTree website

### ISSUE THREAD

**Issue by MichalVasut** [wikitree/wikitree-dynamic-tree#102]
probably relevant for @bcaseyrls or @Clarke-11007 🤔 

Shortly before the talk about Dynamic Tree on saturday, I noticed the integration at Wikitree website (and it was also mentioned there), so I've checked how it is integrated and there are obviously 
- some changes and probably manual interventions (is it the right word? 🤔) that needs to be done.
- separate login cookies for main website and apps server - therefore seperate login (even when I´m logged in at wikitree.com, I still need to login at apps server.)

## Manual changes
- can I somehow assist or help with this (probably boring and tedious) work? e.g. some automation?

## Separate logging cookies

![image](https://user-images.githubusercontent.com/20949562/200268177-745e917e-a2ba-4777-ab5d-afece232ed57.png)

`LoginManager` has [hardcoded login cookie names](https://github.com/wikitree/wikitree-dynamic-tree/blob/0b0e5e744791ef7a55941ec62d2106d8dce639ed/tree.js#L307), but those names can be passed in its constructor, so it can be initialized with different set of names for main website and apps server if needed or can be unified.

Or is this intentional? As for me, I have the same set of username & password for both sites, but this is maybe due to my laziness. 🤔 

But maybe there are some obstacles that prevents this 🤔.

**Comment by bcaseyrls** [comment]
At present, cookies are not shared across the different WikiTree.com sites. So logging into the main www.wikitree.com website does not log you into the API, and vice versa. The initial choice was to keep everything separate, with restrictive cookie settings (specific host, host-only) for security.

It may be worth re-examining some of these choices. We definitely do not want to share the cookies on the primary website with apps.wikitree.com. While access to the apps server isn't completely open, it does host unvetted scripts, and sharing cookies there with www.wikitree.com raises too many possibilities for abuse, or at least confusion.

If we can share cookies between www.wikitree.com and api.wikitree.com, I think that would probably be ok. Both hosts have restricted access, no public scripts, etc.. I'm not sure if this can be done while keeping the cookies away from apps.wikitree.com. If the domain on the cookie is set to .wikitree.com (leading dot), then it can be read by both the www.wikitree.com website and the api.wikitree.com host. But it would **also** have the browser sending the cookies to apps.wikitree.com, which we don't want. I would need to do some additional research and testing, since this is a bit of an edge case for my use of cookies and don't know the answer offhand.

Assuming we can share the login between the website and the API, that still leaves open the question of whether we want to. Certainly doing so simplifies a number of things, not the least of which is having the website version of the tree not need a separate login. But there are are arguments to keeping them separate, so I don't think it's an obvious decision to make without thought.

Even if we share the login/cookie between www and api, that won't help pages hosted on apps (or elsewhere). Those will not have the shared cookies, and will need to store their own state about the user's id. I suppose there could be an API function that queries for what the ID is of the signed-in user, but that feels like a security issue I'd have to think about more carefully.

**Comment by MichalVasut** [comment]
Yeah, sure - what you are saying makes sense.

**Comment by GeoffRiley** [comment]
For what it's worth, I feel that the security of the main server far outstrips the need for any form of cookie sharing. People only actually need to login on the apps server if they are attempting to reach data that is not public, which is generally if you're working on living people.  The reading of protected profiles (as far as I am aware) have no restrictions that require being logged in.

**Comment by MichalVasut** [comment]
Okay, no objection with that.

And the first part? Changes that needs to be done after the merge into the trunk? Is it lot of work or can I help with some automation of the process?

**Comment by bcaseyrls** [comment]
@MichalVasut I'm not sure what changes you're suggesting to automate or help with.

**Comment by MichalVasut** [comment]
@bcaseyrls it doesn't look like it's the same code  at main server (aka copy & paste) as at apps server. Or is it?

**Comment by bcaseyrls** [comment]
The WikiTree website version (e.g. https://www.wikitree.com/treewidget/Hamill-277/7) is running the same view code. The only thing that is different is that instead of "index.html" it's a WikiTree page built from a template with the usual WikiTree "chrome" of menus, footers, etc.. In particular the top includes the various drop-down menus (and the generic profile search box) of the rest of WikiTree.com. But the view itself is the same code as on https://apps.wikitree.com/apps/wikitree-dynamic-tree/.

**Comment by MichalVasut** [comment]
> it's a WikiTree page built from a template with the usual WikiTree "chrome" of menus, footers, etc.. In particular the top includes the various drop-down menus (and the generic profile search box) of the rest of WikiTree.com.

OK, so there is change, but from your description, it's minor and not bothering you or you already have some mechanism to change things automatically - if that's the case, I'm closing the issue.
