### ISSUE TITLE
Fix death date for living persons in `Printer Friendly` view

### ISSUE THREAD

**Issue by MichalVasut** [wikitree/wikitree-dynamic-tree#83]
It's not really pretty for living persons to show `[unknown]`  as death date - show only date of birth.

As for birth date - fix also that - it could be restricted by privacy settings and shown only as decade ...

![image](https://user-images.githubusercontent.com/20949562/198244835-dceab6c3-9b60-43d7-b695-073593dfab5a.png)  ![image](https://user-images.githubusercontent.com/20949562/198244944-d5a062d6-5d2d-4e2d-87ce-a4c0100e1ca0.png)

https://apps.wikitree.com/apps/wikitree-dynamic-tree/#name=Schwarzenegger-1&view=printer-friendly

Sidenote - as a proud Czech, I must point that out! - check his great grand father and where he is from 👍 🇨🇿 

![image](https://user-images.githubusercontent.com/20949562/198245934-a20eb387-69e7-4e3d-9012-9af4453b0aee.png)

**Comment by harrislineage** [comment]
Tagging @GeoffRiley since he is not showing up as an option for Assignee.

**Comment by MichalVasut** [comment]
> Tagging @GeoffRiley since he is not showing up as an option for Assignee.

I can fix that, its my view and I would assign myself if I could - I've created the issue just because I don't have time now.

**Comment by harrislineage** [comment]
> I can fix that, its my view and I would assign myself if I could

Oh!! Sorry about that. Geoff made the family group sheet 🤦‍♂️

**Comment by bcaseyrls** [comment]
Dates on WikiTree are fuzzy. The dates themselves can be missing the day and/or month portion. For profiles limited by privacy, you might only have the rounded "BirthDateDecade" and "DeathDateDecade" fields. The dates also have DataStatus values. For BirthDate, these are "guess" (about/uncertain), "certain" (exact/certain), "before" (before this date), "after" (after this date), and "blank" (blank for extra privacy). For DeathDate we have similar values, but "guess" means "about/uncertain but non-living", and "blank" means "blank because still living".

So instead of "unknown" for an empty DeathDate field, we might want just empty string, because there is no death date. Or it might be known, but hidden, or known but limited to the Decade version. Or it might actually be unknown.

On the server side we have a "Fuzzy Date" version of birth/death date that gets used on some pages. This is formatted as "Month Day, Year" if we have all data, just "Month Year" if we don't have the day, and just "Year" if that's all we have. But that function doesn't take into account the DataStatus (though it is in various code and templates on the site).

Possibly a new handful of Derived value as available fields (https://github.com/wikitree/wikitree-api/blob/main/getProfile.md) would be useful. But if individual views want their own formatting of the dates, I think we'll need to handle all of these variations locally in the app rather than server-side.

**Comment by GeoffRiley** [comment]
The dates certainly cause a little headache… but nothing like the headache that would ensue if the date fields were as free format as people continue to ask for!  If you haven't got the time to look at it @harrislineage, then I'm willing to tackle the dates for you.

It is the sort of thing that would ideally be pulled out into a sub-module within the `window` hierarchy to be more easily available to all.  I could take a look at that instead if that's okay with you @bcaseyrls?

**Comment by Clarke-11007** [comment]
I've got a function I created for the Fan Chart that spits out dates in
multiple formats, based on what is available to start with - and the
desired format requested.  The one thing it doesn't do yet (which I was
intending to add) was the qualifiers where appropriate (about / before /
after).  Death dates are left blank if still living or not available
(though that might be a case where "d. Unknown" is more reflective of the
truth if we know the person is deceased.


function is called getSettingsDateAndPlace(person, dateType)
and it does also handle places at the same time, which was my use case.

Feel free to use / abuse it  / or ignore it if you've already solved the
problem!  Again - an example of something that's probably happening
multiple times across the various trees which we can tighten up eventually.

 - Greg

**Comment by MichalVasut** [comment]
I've already done almost the same with function [`wtDate`](https://github.com/wikitree/wikitree-dynamic-tree/blob/main/WikiTreeAPI.js#L15), but there are still some nuances that I missed - especially privacy and its influence on dates...
