### ISSUE TITLE
Bad links in `Family group view`

### ISSUE THREAD

**Issue by MichalVasut** [wikitree/wikitree-dynamic-tree#89]
Links pointing at WikiTree profile have badly constructed url.

1. Go to Queen Elizabeth II. Family group view: https://apps.wikitree.com/apps/wikitree-dynamic-tree/#name=Windsor-1&view=familygroup
2. Click the link with her name (under profile photo)
3. You'll be redirected to `https://www.wikitree.com/Windsor-1`, which is not correct url for profile

Correct url is `https://www.wikitree.com/wiki/Windsor-1`

PS: the url is missing the `/wiki` part, in the middle.

**Comment by GeoffRiley** [comment]
I'm not sure how I missed that, it must have gone in one of my refactorings: it certainly had previously worked (with the 'wiki').  Step of testing miss.  Yet another argument for a need to find a method of automatic testing.

**Comment by MichalVasut** [comment]
> Yet another argument for a need to find a method of automatic testing.

If you enjoying writing test, try this: https://playwright.dev/ (our frontend guys use it at work).

But as for me - yeah I acknowledge the benefits of testing, but its boooooooring :-)

**Comment by GeoffRiley** [comment]
Haha! Yes, writing tests is extremely tedious… the last place that I actually worked at was doing Ruby on Rails and used something called 'Cucumber' in which you were intended to 'tell stories' to represent the various tests.  At first it seemed quite a good idea but after a hundred or so times of putting together something saying 'I have an account called bert with £500 in it and…' it very quickly starts to lose it'd shine. :)

I'm quite sure that it wasn't being used to the best of its capabilities, because there's no way the tests for a language so famous for promoting 'DRY' qualities should have so much repetition in its testing. ;)

I'll take a closer look at Playwright, I think that overall we do need some testing, even if I'm not necessarily the man for the job, maybe I can start the ball rolling.
